#!/bin/sh

case "$1" in
    up)
	kubectl run --image rkalyana/arpspoof-server --port 3000 arpspoof-server
	kubectl expose deployment arpspoof-server --type NodePort
	;;
    down)
	kubectl delete deployment arpspoof-server
	kubectl delete service arpspoof-server
	;;
    *)
	echo "Usage: server up|down"
	;;
esac
